services:
  - type: web
    name: coach-position-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate --noinput
    startCommand: gunicorn coach_position.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: coach_position.settings
      - key: DJANGO_DEBUG
        value: "False"
