# Generated by Django 5.0.6 on 2026-04-15 14:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_hash', models.CharField(db_index=True, max_length=64)),
                ('normalized_sequence', models.JSONField(default=list)),
                ('support_count', models.PositiveIntegerField(default=0)),
                ('score_breakup', models.JSONField(default=dict)),
                ('final_score', models.FloatField(default=0.0)),
                ('last_evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('division', models.CharField(max_length=120)),
                ('zone', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['division', 'zone'], name='ops_station_divisio_e7127d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('contributor', 'Contributor'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer'), ('admin', 'Admin')], default='contributor', max_length=24)),
                ('reliability_score', models.FloatField(default=0.5)),
                ('reliability_events', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('home_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ops.station')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TrainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(max_length=12)),
                ('train_name', models.CharField(blank=True, max_length=180)),
                ('journey_date', models.DateField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('scheduled_departure', models.DateTimeField(blank=True, null=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_services', to='ops.station')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_services', to='ops.station')),
                ('target_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_services', to='ops.station')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStopRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_ranks', to='ops.station')),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_ranks', to='ops.trainservice')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_band', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('score_delta', models.FloatField(default=0.0)),
                ('reason_codes', models.JSONField(default=list)),
                ('reason_details', models.JSONField(default=dict)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('runner_up_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.candidatecomposition')),
                ('selected_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ops.candidatecomposition')),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_snapshots', to='ops.trainservice')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('locked', 'Locked')], default='open', max_length=16)),
                ('top_candidates', models.JSONField(default=list)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='ops.trainservice')),
            ],
        ),
        migrations.CreateModel(
            name='CoachSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('physical_check', 'Physical Check'), ('tte_onboard', 'TTE Onboard'), ('enroute_station', 'Enroute Station'), ('origin_station', 'Origin Station'), ('forwarded_message', 'Forwarded Message')], max_length=24)),
                ('raw_text', models.TextField(blank=True)),
                ('normalized_sequence', models.JSONField(default=list)),
                ('sequence_hash', models.CharField(db_index=True, max_length=64)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_submissions', to=settings.AUTH_USER_MODEL)),
                ('report_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_submissions', to='ops.station')),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ops.trainservice')),
            ],
        ),
        migrations.AddField(
            model_name='candidatecomposition',
            name='train_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ops.trainservice'),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('composition_change', 'Composition Change'), ('conflict_low_confidence', 'Low Confidence Conflict'), ('confidence_drop', 'Confidence Drop')], max_length=32)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal')], default='normal', max_length=12)),
                ('previous_sequence', models.JSONField(default=list)),
                ('new_sequence', models.JSONField(default=list)),
                ('confidence_before', models.CharField(blank=True, max_length=16)),
                ('confidence_after', models.CharField(blank=True, max_length=16)),
                ('dedupe_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ack_at', models.DateTimeField(blank=True, null=True)),
                ('ack_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ops.trainservice')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='ops_auditev_entity__6e6327_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(default='webpush', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='ops_devicet_user_id_d0d08e_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='push', max_length=16)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ops.alertevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='ops_notific_status_18bd9c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'user', 'channel'), name='uniq_alert_user_channel'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'is_active'], name='ops_userpro_role_2ca9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainservice',
            index=models.Index(fields=['journey_date', 'target_station'], name='ops_trainse_journey_8756c0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainservice',
            index=models.Index(fields=['scheduled_arrival'], name='ops_trainse_schedul_540aac_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainservice',
            constraint=models.UniqueConstraint(fields=('train_no', 'journey_date', 'target_station'), name='uniq_train_journey_target'),
        ),
        migrations.AddIndex(
            model_name='routestoprank',
            index=models.Index(fields=['train_service', 'rank'], name='ops_routest_train_s_b70e29_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestoprank',
            constraint=models.UniqueConstraint(fields=('train_service', 'station'), name='uniq_service_station_rank'),
        ),
        migrations.AddConstraint(
            model_name='routestoprank',
            constraint=models.UniqueConstraint(fields=('train_service', 'rank'), name='uniq_service_rank'),
        ),
        migrations.AddIndex(
            model_name='decisionsnapshot',
            index=models.Index(fields=['train_service', '-effective_at'], name='ops_decisio_train_s_0b52b0_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionsnapshot',
            index=models.Index(fields=['confidence_band'], name='ops_decisio_confide_1d793b_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictcase',
            index=models.Index(fields=['status', 'opened_at'], name='ops_conflic_status_8e2d78_idx'),
        ),
        migrations.AddIndex(
            model_name='coachsubmission',
            index=models.Index(fields=['train_service', 'submitted_at'], name='ops_coachsu_train_s_2fd122_idx'),
        ),
        migrations.AddIndex(
            model_name='coachsubmission',
            index=models.Index(fields=['train_service', 'sequence_hash'], name='ops_coachsu_train_s_6b0284_idx'),
        ),
        migrations.AddIndex(
            model_name='coachsubmission',
            index=models.Index(fields=['source_type', 'report_station'], name='ops_coachsu_source__dc73eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachsubmission',
            constraint=models.UniqueConstraint(fields=('submitted_by', 'idempotency_key'), name='uniq_submitter_idempotency'),
        ),
        migrations.AddIndex(
            model_name='candidatecomposition',
            index=models.Index(fields=['train_service', '-final_score'], name='ops_candida_train_s_f0e41e_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatecomposition',
            constraint=models.UniqueConstraint(fields=('train_service', 'sequence_hash'), name='uniq_candidate_per_service'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['priority', 'created_at'], name='ops_alertev_priorit_adba5a_idx'),
        ),
    ]
