# Generated by Django 5.0.6 on 2026-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecomposition',
            name='sequence_signature',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='coachsubmission',
            name='sequence_signature',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
