# Generated by Django 5.0.6 on 2026-04-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_candidatecomposition_sequence_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainservice',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_services', to='ops.station'),
        ),
        migrations.AlterField(
            model_name='trainservice',
            name='origin_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_services', to='ops.station'),
        ),
        migrations.AlterField(
            model_name='trainservice',
            name='scheduled_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainservice',
            name='target_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_services', to='ops.station'),
        ),
    ]
