# Generated by Django 5.0.6 on 2026-04-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_trainservice_destination_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachsubmission',
            name='report_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_submissions', to='ops.station'),
        ),
    ]
