# Generated by Django 5.0.6 on 2026-04-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_coachsubmission_report_station_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Digits only preferred; used for sign-in when set.', max_length=20, null=True, unique=True),
        ),
    ]
